version: "2"

services:
  main-nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: coraggio_nginx
    restart: always
    external_links:
      - coraggio_nginx
    networks:
      - default
      - coraggio_default
    volumes:
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./html:/var/www/html
    ports:
     - "80:80"

networks:
  coraggio_default:
    external: true  
